name: Add new pr or issue to project board 

on:
  issues: {types: [opened]}
  pull_request: {types: [opened]}

jobs:
  add-to-project:
    uses: lambdaisland/open-source/.github/workflows/add-to-project-board.yml@main
    secrets: inherit
    
